 ## nsmallest and nlargest
### This function display 3 smallest and 3 largest values from the dataframe

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
...     "Student": ['John', 'Jennifer', 'Jeff', 'Joshua', 'Jack', 'Jeremy', 'Jason'],
...     "Score": [95, 100, 94, 99, 88, 92, 89]
... })

In [4]:
df.nlargest(3, "Score")

    Student  Score
1  Jennifer    100
3    Joshua     99
0      John     95

----

## nsmallest and nlargest
### One time, I needed to find out the largest records by group. For instance, suppose that we have the following DataFrame. I want to extract the records whose scores are the highest in their respective groups.

In [6]:
df = pd.DataFrame({
...     "group": [1, 1, 1, 2, 2, 2, 3, 3, 3],
...     "name": ["A1", "B1", "C1", "A2", "B2", "C2", "A3", "B3", "C3"],
...     "score": [97, 93, 92, 94, 95, 93, 100, 92, 93]
... })
df.head()

   group name  score
0      1   A1     97
1      1   B1     93
2      1   C1     92
3      2   A2     94
4      2   B2     95

In [8]:
## Complicated Way : 
df.groupby("group")["score"].max()

group
1     97
2     95
3    100
Name: score, dtype: int64

In [10]:
## Easy Way 
record_indices = df.groupby("group")["score"].idxmax()
record_indices

group
1    0
2    4
3    6
Name: score, dtype: int64

---
##  qcut
### 
When we deal with continuous variables, it’s sometimes necessary to create ordinal values based on the quantiles of the existing numeric values. <br> Theoretically, some people, including me initially, may tend to find out the quantiles of a certain column and create the categorical column by hard-coding the cutoffs. <br>
However, pandas has an easy option to achieve this operation  <br> — using the qcut function, which create distinct values based on their rankings. Using the DataFrame that we defined in the previous section, <br> we can dichotomize the data based on the Score column, as shown below.

In [12]:
df["score_dichotomized"] = pd.qcut(df["score"], 2, labels=['bottom50', 'top50'])
df

   group name  score score_dichotomized
0      1   A1     97              top50
1      1   B1     93           bottom50
2      1   C1     92           bottom50
3      2   A2     94              top50
4      2   B2     95              top50
5      2   C2     93           bottom50
6      3   A3    100              top50
7      3   B3     92           bottom50
8      3   C3     93           bottom50

---

## date_range
### Suppose that I need to create the dates for the first week in 2021, as the index of a DataFrame. Here’s a possible solution.

In [14]:
pd.DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04', '2021-01-05', '2021-01-06', '2021-01-07'], dtype='datetime64[ns]', freq=None)

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06', '2021-01-07'],
              dtype='datetime64[ns]', freq=None)

---

In [15]:

INPUT_IMAGE_URL = "https://storage.googleapis.com/cloud-ml-data/img/openimage/3/2520/3916261642_0a504acd60_o.jpg" #@param {type:"string"}
DETECTION_THRESHOLD = 0.3 #@param {type:"number"}